openapi: 3.0.3
info:
  title: CodeReady Dependency Analytics API
  description: Vulnerability analysis with Red Hat CodeReady Dependency Analytics
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 3.0.0
servers:
- url: http://crda-backend-crda.apps.sssc-cl01.appeng.rhecoeng.com/api/v3/
  description: Production server
- url: http://localhost:8080/api/v3/
  description: Local development
paths:
  /component-analysis/{pkgManager}:
    post:
      operationId: componentAnalysis
      summary: Performs a vulnerability for the provided components
      parameters:
      - name: pkgManager
        in: path
        description: Package manager related to the provided packages
        required: true
        schema:
          enum:
          - maven
          type: string
        example: maven        
      - name: providers
        in: query
        description: List of vulnerability providers to get the report from
        required: false
        schema:
          enum:
          - snyk
          - tidelift
          type: string
        example: snyk
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComponentRequest'
        required: true
      responses:
        '200': 
          description: Successful component analysis report
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DependencyReport'
        '422':
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
                description: Error message
  /dependency-analysis/{pkgManager}:
    post:
      operationId: dependencyAnalysis
      summary:  Takes a client-resolved dependency graph to perform a full stack analysis from all the available Vulnerability sources
      parameters:
      - name: pkgManager
        in: path
        description: Package manager related to the provided packages
        required: true
        schema:
          enum:
          - maven
          type: string
        example: maven
      - name: providers
        in: query
        description: List of vulnerability providers to get the report from
        required: false
        schema:
          enum:
          - snyk
          - tidelift
          type: string
        example: snyk
      requestBody:
        required: true
        description: Dependency graph in DOT format
        content:
          text/vnd.graphviz:
            schema:
              type: object
      responses:
        '200':
          description: Full dependency analysis from all the available providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DependencyReport'
            text/html:
              schema:
                type: object
components:
  schemas:
    ComponentRequest:
      type: array
      items:
        $ref: '#/components/schemas/PackageRef'
    PackageRef:
      type: object
      properties:
        name:
          type: string
          description: <groupId>:<artifactId> for Java packages
          example: org.jgroups:jgroups
        version:
          type: string
          description: Package version
          example: 5.2.0.Final
    DependencyReport:
      type: object
      properties:
        ref:
          $ref: '#/components/schemas/PackageRef'
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'
        transitive:
          type: array
          items:
            $ref: '#/components/schemas/TransitiveDependencyReport'
        recommendations:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Recommendation'
    Issue:
      type: object
      properties:
        id:
          type: string
        source:
          type: string
        cves:
          type: array
          items:
            type: string
        rawData:
          type: object
    TransitiveDependencyReport:
      type: object
      properties:
        ref:
          $ref: '#/components/schemas/PackageRef'
        issues:
          type: array
          items:
            $ref: '#/components/schemas/Issue'
        recommendations:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Recommendation'
    Recommendation:
      type: object
      properties:
        issueRef:
          type: string
        mavenPackage:
          $ref: '#/components/schemas/PackageRef'
        productStatus:
          type: string