apiVersion: v1
kind: Namespace
metadata:
  name: exhort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exhort
  namespace: exhort
  labels:
    app: exhort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exhort
  template:
    metadata:
      labels:
        app: exhort
    spec:
      containers:
      - name: exhort
        image: quay.io/ecosystem-appeng/exhort:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: API_SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: exhort-secret
              key: api-snyk-token
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exhort
  name: exhort
  namespace: exhort
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: exhort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: exhort
  name: dev
  namespace: exhort
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: exhort