---
name: Inform CLI of OpenAPI spec change

on:
  push:
    branches:
      - main
    paths:
      - "api-spec/v3/openapi.yaml"

jobs:
  inform_cli_spec_change:
    runs-on: ubuntu-latest
    name: Dispatch event for CLI
    if: github.repository == 'RHEcosystemAppEng/exhort'
    steps:
      - name: Dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CRDA_CLI_REPO_PAT }}
          script: |
            ['crda-java-api', 'crda-javascript-api'].forEach(async repo => {
              await github.rest.repos.createDispatchEvent({
                owner: "RHEcosystemAppEng",
                repo: repo,
                event_type: "backend-openapi-spec-modified"
              })
            })
